// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnX_8BSl0rrl-LhlKltQH4ls06q1p7zto',
    appId: '1:8175198105:web:7929d047eabf8a7c49fd08',
    messagingSenderId: '8175198105',
    projectId: 'pc-builder-2c0a4',
    authDomain: 'pc-builder-2c0a4.firebaseapp.com',
    databaseURL: 'https://pc-builder-2c0a4-default-rtdb.firebaseio.com',
    storageBucket: 'pc-builder-2c0a4.appspot.com',
    measurementId: 'G-LP3LDZYDV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdqvqTfuCoF2NtGWzzzC3a95tJdy-Jalw',
    appId: '1:8175198105:android:93d3fc4493f270a449fd08',
    messagingSenderId: '8175198105',
    projectId: 'pc-builder-2c0a4',
    databaseURL: 'https://pc-builder-2c0a4-default-rtdb.firebaseio.com',
    storageBucket: 'pc-builder-2c0a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhzbswKgYjVizMCHX9JOXcqDI9LQMs454',
    appId: '1:8175198105:ios:10ff89f2996b612c49fd08',
    messagingSenderId: '8175198105',
    projectId: 'pc-builder-2c0a4',
    databaseURL: 'https://pc-builder-2c0a4-default-rtdb.firebaseio.com',
    storageBucket: 'pc-builder-2c0a4.appspot.com',
    iosClientId: '8175198105-lfcrs4m32depud773amcf9ais020d2ts.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhzbswKgYjVizMCHX9JOXcqDI9LQMs454',
    appId: '1:8175198105:ios:10ff89f2996b612c49fd08',
    messagingSenderId: '8175198105',
    projectId: 'pc-builder-2c0a4',
    databaseURL: 'https://pc-builder-2c0a4-default-rtdb.firebaseio.com',
    storageBucket: 'pc-builder-2c0a4.appspot.com',
    iosClientId: '8175198105-lfcrs4m32depud773amcf9ais020d2ts.apps.googleusercontent.com',
    iosBundleId: 'com.example.fyp',
  );
}
